# Generated by Django 4.1.5 on 2023-02-28 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_tickethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket'),
        ),
    ]
