# Generated by Django 4.1.5 on 2023-02-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('created', 'created'), ('updated', 'updated')], max_length=15, null=True),
        ),
    ]
